[package]
name = "nickel2rust"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
bevy.workspace = true
nickel-lang-core = "0.16"
typify = "0.6" 
serde_json = "1.0"
ignore = "0.4"
pretty = "0.12"
insta = { version = "1.34", features = ["json", "yaml"] }
